import {gameFields} from './main-sync.js';
import {calibrate,project,position,broadcast,demoPoints,WIDTH} from './math.js';
import {publish} from './bus.js';
import './renderer.js';
const $=s=>document.querySelector(s),video=$('#video'),synthetic=$('#synthetic'),stage=$('#stage'),pickCanvas=$('#picks'),ctx=synthetic.getContext('2d'),pickCtx=pickCanvas.getContext('2d');
const defaults=()=>({possession:'away',directionOfPlay:'RIGHT',down:1,distance:10,ballPosition:45,awayTeam:{color:'#266bb1'},homeTeam:{color:'#176b64'},fieldGoalRange:null,fieldGoalLabel:'FG RANGE',customGraphics:[],graphicsVisibility:{los:{visible:true,color:'#294fae',opacity:.9,width:.30},firstDown:{visible:true,color:'#e5e300',opacity:.9,width:.30},downDistance:true,distanceMarkers:false,redZone:false,redZoneMode:'line',possession:false,custom:true,fieldGoal:{visible:false,color:'#f1a752',opacity:.8,width:.18}}});
let preview=defaults(),program=structuredClone(preview),active='CAM1',points=[],picking=false,logo='',epoch=0,sourceReady=true;
const demoH=calibrate(demoPoints).h,cameras=Object.fromEntries(['CAM1','CAM2','CAM3'].map(id=>[id,{id,kind:'synthetic',h:demoH,points:[],name:'Test field',url:null,stream:null,time:0}]));
let mainFields=null,lastMain=0,syncError='Open the graphics control panel to connect.';
const mainChannel=new BroadcastChannel('wld-ar-game:'+new URL('../',import.meta.url).pathname);
mainChannel.onmessage=event=>{if(event.data?.kind!=='game')return;try{mainFields=gameFields(event.data);lastMain=Date.now();syncError='';Object.assign(preview,mainFields);Object.assign(program,mainFields);fill();send();}catch(e){lastMain=0;syncError=e.message;send();}};
mainChannel.postMessage({kind:'request'});
setInterval(()=>mainChannel.postMessage({kind:'request'}),1500);
const current=()=>cameras[active];
function message(t,error=false){$('#message').textContent=t;$('#message').className=error?'error':'success';}
function send(){const c=current(),connected=Date.now()-lastMain<3000&&mainFields;
 const safe=state=>{const out=structuredClone(state);if(mainFields)Object.assign(out,mainFields);if(!connected||!mainFields.gameDataValid){for(const key of ['los','firstDown','fieldGoal'])out.graphicsVisibility[key].visible=false;for(const key of ['downDistance','distanceMarkers','redZone','possession'])out.graphicsVisibility[key]=false;}return broadcast(out);};
 $('#main-sync-status').textContent=connected?`SYNCED · ${mainFields.possession.toUpperCase()} · ${mainFields.down} & ${mainFields.distance}`:(syncError||'Main panel disconnected — game markers hidden');
 publish({preview:safe(preview),program:safe(program),activeCamera:active,output:{width:1920,height:1080},cameras:[{id:active,homography:c.h,calibrationValid:!!c.h,status:sourceReady?'ONLINE':'NO CAMERA',paused:c.kind==='synthetic'||video.paused,frameAgeMs:0}]});$('#cal-status').textContent=c.h?'Field graphics aligned · fixed view':'Video playback ready · use Align field below when you want AR lines';}
setInterval(send,250);
function drawDemo(){ctx.fillStyle='#12201b';ctx.fillRect(0,0,1920,1080);const polygon=(pts,fill)=>{ctx.beginPath();pts.forEach((p,i)=>ctx[i?'lineTo':'moveTo'](...project(demoH,...p)));ctx.closePath();ctx.fillStyle=fill;ctx.fill();};for(let x=0;x<120;x+=5)polygon([[x,0],[x+5,0],[x+5,WIDTH],[x,WIDTH]],x%10?'#356f36':'#306530');ctx.strokeStyle='#d8e3d4';ctx.lineWidth=2;for(let x=0;x<=120;x+=5){ctx.beginPath();ctx.moveTo(...project(demoH,x,0));ctx.lineTo(...project(demoH,x,WIDTH));ctx.stroke();}for(const y of [0,WIDTH]){ctx.beginPath();ctx.moveTo(...project(demoH,0,y));ctx.lineTo(...project(demoH,120,y));ctx.stroke();}ctx.fillStyle='#d8e3d4';ctx.font='22px Arial';for(let x=10;x<120;x+=10)for(const y of[7,46])ctx.fillText(String(x),...project(demoH,x,y));ctx.font='20px Arial';ctx.fillText('WLD TEST FIELD · NUMBERS = FIELD X · NO CAMERA REQUIRED',30,40);}
function showPoints(){pickCtx.clearRect(0,0,1920,1080);pickCtx.font='28px Arial';points.forEach((p,i)=>{pickCtx.fillStyle='#ffda78';pickCtx.beginPath();pickCtx.arc(...p.image,8,0,7);pickCtx.fill();pickCtx.fillText(String(i+1),p.image[0]+12,p.image[1]-12);});$('#point-list').textContent=points.map((p,i)=>`${i+1}: FIELD ${p.field.join(', ')} → IMAGE ${p.image.map(Math.round).join(', ')}`).join(' | ');}
function clearCalibration(reason){if(current().kind!=='synthetic')current().h=null;points=[];picking=false;stage.classList.remove('calibrating');showPoints();if(reason)message(reason);send();}
function detach(){video.pause();video.srcObject=null;video.removeAttribute('src');video.load();}
function showSource(){sourceReady=false;epoch++;const c=current();detach();points=c.points||[];showPoints();video.style.display=c.kind==='synthetic'?'none':'block';synthetic.style.display=c.kind==='synthetic'?'block':'none';$('#source-status').textContent=c.name;if(c.kind==='synthetic'){sourceReady=true;drawDemo();}else if(c.kind==='file'&&c.url){video.src=c.url;video.load();}else if(c.kind==='camera'&&c.stream){video.srcObject=c.stream;video.play().catch(e=>message('Click Play to start camera: '+e.message,true));}else message('Select a local video or connect a camera for this slot.',true);send();}
video.onloadeddata=()=>{sourceReady=true;$('#source-status').textContent=`${current().name} · ${video.videoWidth} × ${video.videoHeight} · ready`;send();};
video.onloadedmetadata=()=>{if(current().kind==='file'&&current().time>0&&current().time<video.duration)video.currentTime=current().time;};
video.onerror=()=>{sourceReady=false;const codes={1:'Playback was interrupted',2:'Unable to read the selected file',3:'Browser could not decode this video codec',4:'Unsupported video codec or damaged file'};message((codes[video.error?.code]||'Video could not load')+'. Try an H.264 MP4 or VP9 WebM. No upload server is involved.',true);$('#source-status').textContent='VIDEO ERROR';send();};
video.ontimeupdate=()=>{if(Number.isFinite(video.duration)&&video.duration>0){$('#seek').value=video.currentTime/video.duration*1000;$('#time').textContent=`${video.currentTime.toFixed(1)} / ${video.duration.toFixed(1)} seconds`;current().time=video.currentTime;}};
video.onended=()=>{message('Clip ended. Press Restart or Play to replay.');if($('#loop').checked){clearCalibration('Loop restarted — recalibrate after a change of view.');video.currentTime=0;video.play().catch(e=>message(e.message,true));}};
async function play(){if(current().kind==='synthetic')return message('The test field is static. Choose a video or camera to play motion.');if(video.ended){clearCalibration('Replay restarted — field alignment cleared.');video.currentTime=0;}try{await video.play();message('Playing '+current().name);}catch(e){message('Playback could not start: '+e.message,true);}}
$('#play').onclick=play;$('#pause').onclick=()=>{video.pause();message('Video paused.');};$('#restart').onclick=()=>{if(current().kind!=='file')return;clearCalibration('Restarted — align field lines for the opening frame.');video.currentTime=0;play();};$('#seek').oninput=()=>{if(current().kind!=='file'||!Number.isFinite(video.duration))return;video.pause();clearCalibration('Seeked — align field lines again for this view.');video.currentTime=+$('#seek').value/1000*video.duration;};
function release(c){if(c.url)URL.revokeObjectURL(c.url);c.stream?.getTracks().forEach(t=>t.stop());c.url=null;c.stream=null;}
$('#file').onchange=async()=>{const f=$('#file').files[0];if(!f)return;const c=current();release(c);Object.assign(c,{kind:'file',name:f.name,url:URL.createObjectURL(f),time:0,h:null,points:[]});showSource();message('Opening '+f.name+'…');$('#file').value='';stage.scrollIntoView({block:'center',behavior:'smooth'});await play();};
$('#camera').onchange=()=>{current().time=video.currentTime||0;active=$('#camera').value;picking=false;stage.classList.remove('calibrating');showSource();};
$('#demo').onclick=()=>{release(current());Object.assign(current(),{kind:'synthetic',name:'Test field',h:demoH,points:[]});showSource();message('Test field ready with known calibration.');};
$('#webcam').onclick=async()=>{if(!navigator.mediaDevices?.getUserMedia)return message('Camera access needs localhost or HTTPS. Open this page with Live Server on this computer.',true);const id=$('#devices').value,slot=active,token=++epoch;try{const stream=await navigator.mediaDevices.getUserMedia({video:id?{deviceId:{exact:id}}:true,audio:false});if(slot!==active||token!==epoch){stream.getTracks().forEach(t=>t.stop());return;}release(current());Object.assign(current(),{kind:'camera',name:'Live camera',stream,h:null,points:[]});showSource();const devices=await navigator.mediaDevices.enumerateDevices();$('#devices').replaceChildren(new Option('Default camera',''),...devices.filter(d=>d.kind==='videoinput').map((d,i)=>new Option(d.label||`Camera ${i+1}`,d.deviceId)));$('#devices').value=id;message('Camera connected. Calibrate a fixed view.');}catch(e){message('Camera connection failed: '+e.message,true);}};
$('#pick').onclick=()=>{video.pause();picking=!picking;stage.classList.toggle('calibrating',picking);message(picking?'Enter field X/Y, then click the matching field intersection.':'Point picking stopped.');};
pickCanvas.onclick=e=>{if(!picking||!sourceReady)return;const field=[+$('#field-x').value,+$('#field-y').value];if(field[0]<0||field[0]>120||field[1]<0||field[1]>WIDTH)return message('Point must be inside the field.',true);const r=pickCanvas.getBoundingClientRect();points.push({field,image:[(e.clientX-r.left)*1920/r.width,(e.clientY-r.top)*1080/r.height]});showPoints();};
$('#undo').onclick=()=>{points.pop();showPoints();};$('#calculate').onclick=()=>{try{const result=calibrate(points);current().h=result.h;current().points=structuredClone(points);picking=false;stage.classList.remove('calibrating');pickCtx.clearRect(0,0,1920,1080);message(`Calibration applied · ${result.error.toFixed(2)} px fit error. This alignment applies to the current view.`);send();}catch(e){message(e.message,true);}};$('#reset-cal').onclick=()=>{current().h=null;points=[];current().points=[];showPoints();send();};
function readGame(){const f=new FormData($('#game')),d=Object.fromEntries(f),next=structuredClone(preview);if(mainFields)Object.assign(next,mainFields);for(const key of ['los','firstDown','fieldGoal'])next.graphicsVisibility[key].visible=f.has(key);for(const key of ['downDistance','distanceMarkers','redZone','custom'])next.graphicsVisibility[key]=f.has(key);next.graphicsVisibility.redZoneMode=d.redZoneMode;if(f.has('fieldGoal')&&next.fieldGoalRange===null)throw Error('Set the FG position in the main graphics control panel first');return next;}

function update(){try{preview=readGame();if($('#auto').checked)program=structuredClone(preview);send();message($('#auto').checked?'Updated on program':'Preview updated — press TAKE for program');return true;}catch(e){message(e.message,true);return false;}}
$('#game').onsubmit=e=>{e.preventDefault();update();};$('#game').onchange=update;$('#take').onclick=()=>{if(update()){program=structuredClone(preview);send();message('Taken to program');}};$('#clear').onclick=()=>{for(const [k,v]of Object.entries(program.graphicsVisibility)){if(typeof v==='boolean')program.graphicsVisibility[k]=false;else if(typeof v==='object')v.visible=false;}send();message('Program cleared. Preview retained.');};$('#auto').onchange=()=>{if($('#auto').checked)update();};$('#view').onchange=send;
function list(){const box=$('#items');box.replaceChildren();for(const g of preview.customGraphics){const row=document.createElement('div');row.className='row';const text=document.createElement('span');text.textContent=`${g.type.toUpperCase()} · ${g.text} · X ${g.fieldX}, Y ${g.fieldY}`;const b=document.createElement('button');b.textContent='Remove';b.onclick=()=>{preview.customGraphics=preview.customGraphics.filter(x=>x.id!==g.id);if($('#auto').checked)program=structuredClone(preview);list();send();};row.append(text,b);box.append(row);}}
$('#logo').onchange=async()=>{const f=$('#logo').files[0];if(!f)return;if(f.size>8*1024*1024)return message('Use an image smaller than 8 MB.',true);try{const img=await createImageBitmap(f),c=document.createElement('canvas'),r=Math.min(1,1200/Math.max(img.width,img.height));c.width=Math.round(img.width*r);c.height=Math.round(img.height*r);c.getContext('2d').drawImage(img,0,0,c.width,c.height);logo=c.toDataURL('image/png');img.close();message('Image ready — press Add graphic.');}catch(e){message('Image could not be decoded.',true);}};
$('#custom').onsubmit=e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));if(d.type==='logo'&&!logo)throw Error('Choose an image first');const g={id:crypto.randomUUID(),type:d.type,text:d.text.toUpperCase(),fieldX:+d.fieldX,fieldY:+d.fieldY,width:+d.width,height:+d.height,color:d.color,opacity:.9,points:['line','polygon'].includes(d.type)?JSON.parse(d.points):[],image:d.type==='logo'?logo:''};if(g.points.some(p=>!Array.isArray(p)||p.length!==2||!p.every(Number.isFinite)||p[0]<0||p[0]>120||p[1]<0||p[1]>WIDTH))throw Error('Invalid field points');if(g.type==='line'&&g.points.length!==2)throw Error('Line needs two points');if(g.type==='polygon'&&g.points.length<3)throw Error('Polygon needs at least three points');if(g.type==='polygon'){let sign=0;for(let i=0;i<g.points.length;i++){const a=g.points[i],b=g.points[(i+1)%g.points.length],c=g.points[(i+2)%g.points.length],z=(b[0]-a[0])*(c[1]-b[1])-(b[1]-a[1])*(c[0]-b[0]);if(z&&sign&&Math.sign(z)!==sign)throw Error('Use a convex polygon');if(z)sign=Math.sign(z);}if(!sign)throw Error('Polygon has no area');}preview.customGraphics.push(g);preview.graphicsVisibility.custom=true;$('#game').elements.custom.checked=true;if($('#auto').checked)program=structuredClone(preview);list();send();message('Custom graphic added');}catch(e){message(e.message,true);}};
const saveKey='wld-local-show:'+new URL('.',import.meta.url).pathname;
$('#save').onclick=()=>{try{localStorage.setItem(saveKey,JSON.stringify({preview,program}));message('Show saved in this browser. Video files and camera permissions must be reselected after reload.');}catch(e){message('Could not save: browser storage is full. Use smaller images.',true);}};
$('#load').onclick=()=>{try{const raw=JSON.parse(localStorage.getItem(saveKey));if(!raw?.preview?.graphicsVisibility||!raw?.program?.graphicsVisibility)throw Error('No saved show');preview=raw.preview;program=raw.program;fill();list();send();message('Show restored. Reconnect and recalibrate your camera if needed.');}catch(e){message(e.message,true);}};
function fill(){const f=$('#game').elements,s=preview;for(const k of ['possession','directionOfPlay','down','distance'])f[k].value=s[k];const own=s.directionOfPlay==='RIGHT'?s.ballPosition-10:110-s.ballPosition;f.footballPosition.value=own===50?'50':own<50?'OWN '+own:'OPP '+(100-own);f.awayColor.value=s.awayTeam.color;f.homeColor.value=s.homeTeam.color;for(const k of ['los','firstDown','fieldGoal'])f[k].checked=s.graphicsVisibility[k].visible;for(const k of ['downDistance','distanceMarkers','redZone','custom'])f[k].checked=s.graphicsVisibility[k];f.redZoneMode.value=s.graphicsVisibility.redZoneMode;const fg=s.fieldGoalRange;if(fg===null)f.fgPosition.value='';else{const own=s.directionOfPlay==='RIGHT'?fg-10:110-fg;f.fgPosition.value=own===50?'50':own<50?'OWN '+own:'OPP '+(100-own);}}
window.addEventListener('beforeunload',()=>Object.values(cameras).forEach(release));
if(location.protocol==='file:')message('Open index.html with VS Code Live Server, not by double-clicking the HTML file.',true);
showSource();fill();list();send();

$('#fullscreen').onclick=()=>stage.requestFullscreen().catch(e=>message(e.message,true));
const calKey=()=>saveKey+':cal:'+active;
const sourceIdentity=()=>[current().kind,current().name,video.videoWidth,video.videoHeight].join('|');
$('#save-cal').onclick=()=>{try{if(!current().h)throw Error('Align this view first');localStorage.setItem(calKey(),JSON.stringify({identity:sourceIdentity(),h:current().h,points:current().points}));message('Calibration saved for this source. Reload only at the same camera view.');}catch(e){message(e.message,true);}};
$('#load-cal').onclick=()=>{try{const c=JSON.parse(localStorage.getItem(calKey()));if(!c||c.identity!==sourceIdentity())throw Error('No saved calibration matching this source and resolution');current().h=c.h;points=c.points;current().points=points;showPoints();send();message('Calibration loaded — verify alignment with the current frame before using it.');}catch(e){message(e.message,true);}};
