import {connect} from './bus.js';import{matrixForGL,polygonPoints,project}from './projection.js';import{fieldGraphics}from './graphics.js';
const canvas=document.querySelector('#ar'),gl=canvas.getContext('webgl',{alpha:true,premultipliedAlpha:true,antialias:true});let state,lastMessage=0,fps=0,renderMs=0,frames=0,then=performance.now();
function report(text){const note=document.querySelector('#render-status');if(note&&note.textContent!==text)note.textContent=text;}
if(!gl){report('Graphics unavailable: WebGL could not start.');const note=document.querySelector('#cal-status');if(note)note.textContent='AR rendering unavailable: WebGL is disabled. Video playback is still available.';}else{
const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec2 a; attribute vec2 uv; uniform mat3 H; uniform vec2 resolution; varying vec2 tex; void main(){vec3 p=H*vec3(a,1.0);gl_Position=vec4(2.0*p.x/resolution.x-p.z,p.z-2.0*p.y/resolution.y,0.0,p.z);tex=uv;}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float; uniform sampler2D image; uniform vec4 color; varying vec2 tex;void main(){gl_FragColor=texture2D(image,tex)*color;}'));gl.linkProgram(program);gl.useProgram(program);gl.enable(gl.BLEND);gl.blendFuncSeparate(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE_MINUS_SRC_ALPHA);
const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);for(const [name,offset]of[['a',0],['uv',8]]){const l=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(l);gl.vertexAttribPointer(l,2,gl.FLOAT,false,16,offset);}
const cache=new Map();function texture(source){const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,source);return t;}
const white=document.createElement('canvas');white.width=white.height=1;white.getContext('2d').fillStyle='white';white.getContext('2d').fillRect(0,0,1,1);const solid=texture(white);
function artwork(s){const key=s.image||JSON.stringify([s.text,s.color,s.plate,s.direction,s.style]);if(cache.has(key))return cache.get(key);if(cache.size>150){for(const t of cache.values())if(t)gl.deleteTexture(t);cache.clear();}if(s.image){cache.set(key,null);const img=new Image();img.onload=()=>cache.set(key,texture(img));img.src=s.image;return null;}const c=document.createElement('canvas');c.width=1024;c.height=256;const ctx=c.getContext('2d');if(s.style==='turf'){const left=s.direction==='LEFT';ctx.textAlign='center';ctx.textBaseline='middle';const text=String(s.text).toUpperCase();ctx.font='900 180px Arial';const size=Math.min(180,180*720/ctx.measureText(text).width);ctx.font=`900 ${size}px Arial`;ctx.lineJoin='round';ctx.lineWidth=5;ctx.strokeStyle='rgba(220,226,210,.52)';ctx.fillStyle=s.color;ctx.globalAlpha=.35;ctx.fillText(text,left?635:389,139);ctx.globalAlpha=1;ctx.strokeText(text,left?635:389,139);for(let i=0;i<2;i++){const x=left?150-i*78:850+i*78;ctx.beginPath();ctx.moveTo(x,48);ctx.lineTo(x+(left?-82:82),128);ctx.lineTo(x,208);ctx.lineTo(x+(left?30:-30),208);ctx.lineTo(x+(left?-48:48),128);ctx.lineTo(x+(left?30:-30),48);ctx.closePath();ctx.stroke();}const t=texture(c);cache.set(key,t);return t;}ctx.fillStyle=s.plate||'#122c36';ctx.beginPath();if(s.direction==='LEFT'){ctx.moveTo(1024,30);ctx.lineTo(64,30);ctx.lineTo(0,128);ctx.lineTo(64,226);ctx.lineTo(1024,226);}else{ctx.moveTo(0,30);ctx.lineTo(960,30);ctx.lineTo(1024,128);ctx.lineTo(960,226);ctx.lineTo(0,226);}ctx.closePath();ctx.fill();ctx.fillStyle=s.color||'#ffffff';ctx.font='900 104px Arial';ctx.textAlign='center';ctx.textBaseline='middle';const text=String(s.text||'').toUpperCase();const width=ctx.measureText(text).width;if(width>890)ctx.font=`900 ${104*890/width}px Arial`;ctx.fillText(text,s.direction==='LEFT'?529:495,135);const t=texture(c);cache.set(key,t);return t;}
function draw(s){let points=polygonPoints(s),tex=solid,color=s.color||'#ffffff';if(!points){const x=s.fieldX,y=s.fieldY,w=s.width/2,h=s.height/2;points=[[x-w,y-h],[x+w,y-h],[x+w,y+h],[x-w,y+h]];tex=artwork(s);color='#ffffff';if(!tex)return;}const uv=[[0,1],[1,1],[1,0],[0,0]];const verts=[];for(let i=1;i<points.length-1;i++)for(const k of[0,i,i+1])verts.push(...points[k],...(uv[k]||[0,0]));gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.DYNAMIC_DRAW);gl.bindTexture(gl.TEXTURE_2D,tex);const rgb=color.match(/\w\w/g).map(x=>parseInt(x,16)/255);gl.uniform4f(gl.getUniformLocation(program,'color'),...rgb,s.opacity??1);gl.drawArrays(gl.TRIANGLES,0,verts.length/4);}
const params=new URLSearchParams(location.search);connect(s=>{state=s;lastMessage=performance.now();});
function loop(){const start=performance.now();try{const width=state?.output.width||1920,height=state?.output.height||1080;if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}gl.viewport(0,0,width,height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);if(!state||start-lastMessage>=2000){report('Waiting for AR control data. Keep the AR controller open.');}else{const cam=state.cameras.find(c=>c.id===(params.get('camera')||state.activeCamera));if(!cam?.calibrationValid||!cam.homography){report('No field alignment: select four points before showing field graphics.');}else if(cam.status!=='ONLINE'){report('Waiting for the selected video to load.');}else{gl.uniformMatrix3fv(gl.getUniformLocation(program,'H'),false,matrixForGL(cam.homography));gl.uniform2f(gl.getUniformLocation(program,'resolution'),width,height);const selected=(document.querySelector('#view')?.value==='preview'||params.has('preview'))?state.preview:state.program;const shapes=fieldGraphics(selected);let visible=0;for(const shape of shapes){draw(shape);const pts=polygonPoints(shape)||[[shape.fieldX-shape.width/2,shape.fieldY-shape.height/2],[shape.fieldX+shape.width/2,shape.fieldY+shape.height/2]];const image=pts.map(p=>project(cam.homography,...p));if(image.every(p=>p.every(Number.isFinite))&&Math.max(...image.map(p=>p[0]))>=0&&Math.min(...image.map(p=>p[0]))<=width&&Math.max(...image.map(p=>p[1]))>=0&&Math.min(...image.map(p=>p[1]))<=height)visible++;}report(!shapes.length?'No graphics enabled: check main-panel sync, possession, and AR visibility.':!visible?'Graphics are outside this video frame. Check the main panel ball-on, direction, and alignment yard lines.':`Rendering ${visible} graphic(s) over the video · LOS field X ${selected.lineOfScrimmage}`);}}}catch(error){report('AR rendering error: '+error.message);}
frames++;if(start-then>=1000){fps=Math.round(frames*1000/(start-then));frames=0;then=start;}renderMs=Math.round((performance.now()-start)*100)/100;requestAnimationFrame(loop);}if(gl)loop();

}
