// Browser-only planar field tracking. Vendored OpenCV: see vendor/LICENSE-OpenCV.txt.
let loading;
export function loadTrackingCV(){if(!loading)loading=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=new URL('./vendor/opencv.js',import.meta.url).href;script.onerror=()=>reject(Error('Tracking library missing. Replace the complete ar folder.'));script.onload=()=>{try{const ready=cv=>{if(typeof cv.then==='function')delete cv.then;resolve(cv);};const cv=window.cv;if(cv.Mat)ready(cv);else if(cv.then)cv.then(ready);else cv.onRuntimeInitialized=()=>ready(cv);}catch(e){reject(e);}};document.head.append(script);});return loading;}
export function multiply(a,b){return a.map(row=>b[0].map((_,j)=>row.reduce((v,x,k)=>v+x*b[k][j],0)));}
export function transform(h,x,y){const w=h[2][0]*x+h[2][1]*y+h[2][2];return[(h[0][0]*x+h[0][1]*y+h[0][2])/w,(h[1][0]*x+h[1][1]*y+h[1][2])/w];}
export class FieldTracker{
 constructor(cv){this.cv=cv;this.canvas=document.createElement('canvas');this.canvas.width=640;this.canvas.height=360;this.ctx=this.canvas.getContext('2d',{willReadFrequently:true});this.reset();}
 reset(){this.previous?.delete();this.features?.delete();this.previous=null;this.features=null;this.h=null;this.age=0;}
 capture(source){const w=source.videoWidth||source.width,h=source.videoHeight||source.height;if(!w||!h)throw Error('Video frame is not ready');const scale=Math.min(640/w,360/h);this.ctx.fillStyle='black';this.ctx.fillRect(0,0,640,360);this.ctx.drawImage(source,(640-w*scale)/2,(360-h*scale)/2,w*scale,h*scale);const rgba=this.cv.matFromImageData(this.ctx.getImageData(0,0,640,360)),gray=new this.cv.Mat();this.cv.cvtColor(rgba,gray,this.cv.COLOR_RGBA2GRAY);return{rgba,gray};}
 seeds(rgba,gray){const cv=this.cv,mask=cv.Mat.zeros(360,640,cv.CV_8UC1),out=new cv.Mat(),d=rgba.data;try{for(let y=24;y<306;y++)for(let x=12;x<628;x++){// Turf/marking neighborhoods; excludes score ribbons and most crowd.
 let green=0;for(const [dx,dy] of [[-6,0],[6,0],[0,-6],[0,6]]){const i=((y+dy)*640+x+dx)*4,r=d[i],g=d[i+1],b=d[i+2];if(g>r*1.04&&g>b*1.14&&g>35)green++;}if(green>=3)mask.data[y*640+x]=255;}
 cv.goodFeaturesToTrack(gray,out,180,.015,9,mask,5,false,.04);return out;}finally{mask.delete();}}
 start(source,h){this.reset();const f=this.capture(source);try{this.features=this.seeds(f.rgba,f.gray);if(this.features.rows<18)throw Error('Not enough field detail. Align a wider, sharper field view.');this.previous=f.gray;this.h=h.map(r=>r.slice());return this.features.rows;}catch(e){f.gray.delete();this.reset();throw e;}finally{f.rgba.delete();}}
 update(source){const cv=this.cv;if(!this.previous||!this.h)throw Error('Align field to start tracking');const f=this.capture(source),garbage=[f.rgba,f.gray];try{const next=new cv.Mat(),back=new cv.Mat(),status=new cv.Mat(),error=new cv.Mat(),backStatus=new cv.Mat(),backError=new cv.Mat();garbage.push(next,back,status,error,backStatus,backError);const win=new cv.Size(21,21),criteria=new cv.TermCriteria(cv.TermCriteria_COUNT|cv.TermCriteria_EPS,25,.015);cv.calcOpticalFlowPyrLK(this.previous,f.gray,this.features,next,status,error,win,3,criteria);cv.calcOpticalFlowPyrLK(f.gray,this.previous,next,back,backStatus,backError,win,3,criteria);const a=[],b=[];for(let i=0;i<this.features.rows;i++){const x=this.features.data32F[2*i],y=this.features.data32F[2*i+1],u=next.data32F[2*i],v=next.data32F[2*i+1];if(status.data[i]&&backStatus.data[i]&&error.data32F[i]<24&&Math.hypot(back.data32F[2*i]-x,back.data32F[2*i+1]-y)<1.1&&u>8&&u<632&&v>16&&v<320){a.push(x,y);b.push(u,v);}}
 if(a.length<32)throw Error('Lost field features');const src=cv.matFromArray(a.length/2,1,cv.CV_32FC2,a),dst=cv.matFromArray(b.length/2,1,cv.CV_32FC2,b),inliers=new cv.Mat();garbage.push(src,dst,inliers);const fit=cv.findHomography(src,dst,cv.RANSAC,1.5,inliers,1200,.995);garbage.push(fit);if(fit.empty())throw Error('Cannot estimate field movement');const kept=[],xs=[],ys=[];for(let i=0;i<inliers.rows;i++)if(inliers.data[i]){kept.push(b[2*i],b[2*i+1]);xs.push(a[2*i]);ys.push(a[2*i+1]);}if(xs.length<16||xs.length/(a.length/2)<.65||Math.max(...xs)-Math.min(...xs)<120||Math.max(...ys)-Math.min(...ys)<65)throw Error('Tracking confidence lost');const d=fit.data64F,M=[Array.from(d.slice(0,3)),Array.from(d.slice(3,6)),Array.from(d.slice(6,9))];const corners=[[0,0],[640,0],[640,360],[0,360]].map(p=>transform(M,...p));if(corners.some((p,i)=>!p.every(Number.isFinite)||Math.hypot(p[0]-[0,640,640,0][i],p[1]-[0,0,360,360][i])>90))throw Error('Camera cut or movement too large');
 const move=multiply([[3,0,0],[0,3,0],[0,0,1]],multiply(M,[[1/3,0,0],[0,1/3,0],[0,0,1]]));this.h=multiply(move,this.h);this.previous.delete();this.previous=f.gray;garbage.splice(garbage.indexOf(f.gray),1);this.features.delete();this.age++;this.features=this.age%12===0||kept.length<150?this.seeds(f.rgba,f.gray):cv.matFromArray(kept.length/2,1,cv.CV_32FC2,kept);return{h:this.h,count:xs.length,ratio:xs.length/(a.length/2)};
 }finally{garbage.forEach(m=>m.delete());}}
}
