const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const extraNames={weatherdetail:'Weather · detailed conditions',matchupclean:'Matchup · clean venue ribbon',matchupbadge:'Matchup · event badge',comingupmatchup:'Matchup · coming up',reporterbadge:'Reporter · event badge',languagepromo:'Language / broadcast availability'};
const logo=t=>t.heroLogo||t.logo?`<img src="${esc(t.heroLogo||t.logo)}" alt="${esc(t.name)}">`:`<b>${esc(t.abbr)}</b>`;
const location=s=>[s.branding.city,s.branding.stateAbbr].filter(Boolean).join(', ');
const badge=(s,c)=>`<div class="extra194-badge">${s.branding.networkLogo?`<img src="${esc(s.branding.networkLogo)}" alt="${esc(s.branding.network)}">`:`<b>${esc(s.branding.network||'WLD SPORTS')}</b>`}<span>${esc(c.extraBadge||s.branding.competition||'GAME DAY')}</span></div>`;
function rails(){return `<svg class="extra194-rails" viewBox="0 0 1500 220" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="extra194-metal" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#f5f9fa"/><stop offset=".3" stop-color="#b8cbd3"/><stop offset=".6" stop-color="#6e8793"/><stop offset="1" stop-color="#203844"/></linearGradient></defs><path d="M20 3H1480M3 34L24 163L64 211H490L520 202H580M920 202H980L1010 211H1436L1476 163L1497 34" fill="none" stroke="#273d49" stroke-width="14"/><path d="M20 2H1480M3 34L25 160L66 207H490L520 198H580M920 198H980L1010 207H1434L1475 160L1497 34" fill="none" stroke="#a4b9c3" stroke-width="8"/><path d="M20 0H1480M4 34L26 159L67 204H490L520 195H580M920 195H980L1010 204H1433L1474 159L1496 34" fill="none" stroke="#eef5f6" stroke-width="2"/><path d="M170 203l4 5m8-5l4 5m8-5l4 5M1290 203l4 5m8-5l4 5m8-5l4 5" stroke="#536a77" stroke-width="2"/></svg>`}
function cloud(kind){return `<svg viewBox="0 0 100 60" aria-hidden="true">${kind==='SUNNY'?'<circle cx="50" cy="30" r="19" fill="#f7c92f"/>':'<path d="M25 47C2 45 7 24 25 24C28 4 59 3 66 21C91 16 99 44 79 48Z" fill="#566069" stroke="#dce2df" stroke-width="3"/>'}${kind==='RAIN'?'<path d="M30 52l-4 7m23-7l-4 7m23-7l-4 7" stroke="#b5d7ef" stroke-width="3"/>':''}</svg>`}
export function extraGraphic(s,c){if(!extraNames[c.type])return '';const a=s.teams.away,h=s.teams.home;
if(c.type==='weatherdetail')return `<section class="extra194 weather194"><div class="weather194-face"><header><h1>${esc(c.title||location(s)||'CITY, ST')}</h1><h2>${esc(c.subtitle||s.branding.venue||'VENUE')}</h2></header><div class="weather194-condition">${cloud(c.weatherIcon||'CLOUDY')}<b>${esc(c.weatherForecast||'CLOUDY')}</b></div><div class="weather194-values">${[['TEMP',c.weatherTemp||'52°'],['HUMIDITY',c.weatherHumidity||'54%'],['WIND',c.weatherWind||'SE 8']].map(([label,value])=>`<div><small>${label}</small><strong>${esc(value)}${label==='WIND'?'<em> MPH</em>':''}</strong></div>`).join('')}</div></div><div class="weather194-metal"></div></section>`;
if(c.type==='reporterbadge')return `<section class="extra194 reporter194">${badge(s,c)}<div class="extra194-face"></div>${rails()}<h1>${esc(c.reporterName||s.branding.crew?.find(x=>/sideline/i.test(x.role||''))?.name||'REPORTER NAME')}</h1></section>`;
if(c.type==='languagepromo')return `<section class="extra194 language194"><div class="extra194-face"></div>${rails()}<div class="language194-logo">${s.branding.secondaryLogo||s.branding.networkLogo?`<img src="${esc(s.branding.secondaryLogo||s.branding.networkLogo)}" alt="Network">`:`<b>${esc(s.branding.network||'WLD SPORTS')}</b>`}</div><p>${esc(c.title||'SPANISH LANGUAGE TELECAST')}<br>${esc(c.subtitle||'AVAILABLE ON FOX DEPORTES')}</p></section>`;
const compact=c.type==='comingupmatchup',eventBadge=c.type==='matchupbadge';return `<section class="extra194 matchup194 ${compact?'compact194':''} ${eventBadge?'badge194':''}" style="--away:${esc(a.color)};--home:${esc(h.color)}"><div class="extra194-face"></div>${rails()}${compact||eventBadge?badge(s,c):''}<div class="matchup194-team away">${logo(a)}${eventBadge?`<span>${esc(a.name.replace(a.shortName||'','').trim()||a.name)}</span>`:''}</div><div class="matchup194-team home">${logo(h)}${eventBadge?`<span>${esc(h.name.replace(h.shortName||'','').trim()||h.name)}</span>`:''}</div><div class="matchup194-copy"><h1>${esc(compact?(c.title||'COMING UP'):(a.shortName||a.name)+' vs '+(h.shortName||h.name))}</h1><p>${esc(compact?(a.shortName||a.name)+' vs '+(h.shortName||h.name):[c.title||s.branding.venue,c.subtitle||location(s)].filter(Boolean).join(' - '))}</p></div></section>`;}
