export function createPlaylist({getState,act,stopLineup,esc,graphicNames,render,toast}){
 let selected='',timer=null,deadline=0,remaining=0,running=false,working=false,owned=null,generation=0;
 const items=()=>(getState()?.program.playlist||[]).filter(x=>!['tiers','upcoming'].includes(x.cue.type));
 const current=()=>items().find(x=>x.id===selected)||items()[0];
 function pause(){if(timer){remaining=Math.max(0,deadline-Date.now());clearTimeout(timer);}timer=null;running=false;generation++;renderStatus();}
 function renderStatus(){const el=document.querySelector('#playlist-status');if(el)el.textContent=running?'Playing automatically':remaining?'Paused — graphic stays on air':'Manual playback';}
 function observe(s){if(working||!owned)return;const p=s.program;
  if(p.takeId!==owned.takeId){if(owned.expires&&Date.now()>=owned.expires*1000&&p.graphic.type==='none'&&p.takeId===owned.takeId+1){owned.takeId=p.takeId;return;}pause();owned=null;}
 }
 async function save(rows){pause();await act('playlist_save',{items:rows});render();}
 function schedule(ms){clearTimeout(timer);remaining=ms;deadline=Date.now()+ms;const token=generation;timer=setTimeout(async()=>{timer=null;remaining=0;if(token!==generation||!running)return;try{await advance(true);}catch(e){pause();toast(e.message,true);}},ms);renderStatus();}
 async function take(automatic=false){const item=current();if(!item)return;const token=generation;working=true;stopLineup();try{await act('playlist_take',{id:item.id});selected=item.id;owned={id:item.id,type:item.cue.type,takeId:getState().program.takeId,expires:getState().program.timedGraphic?.until};remaining=0;if(automatic&&token===generation){running=true;schedule(Math.max(item.seconds, item.cue.type==='transition'?Number(item.cue.transitionDuration)||0:0)*1000);}render();}finally{working=false;}}
 async function out(){if(!owned)return;const p=getState().program;if(p.takeId!==owned.takeId){owned=null;return;}working=true;try{if(owned.type==='qbstats')await act('qb_stats_visibility',{visible:false});else if(owned.type==='scorebug')await act('bug',{visible:false});else await act('hide',{});owned=null;}finally{working=false;}}
 async function advance(automatic=false){const row=current();if(!row)return;const token=generation;await out();if(automatic&&token!==generation)return;const index=items().findIndex(x=>x.id===row.id);if(index>=items().length-1){pause();render();toast('Playlist complete.');return;}selected=items()[index+1].id;await take(automatic);}
 function view(){const rows=items(),c=current();return `<section class="card"><h2>Demo playlist</h2><p>Configure a graphic in the library, then add its current preview here. Each item saves its own graphic settings and In/Out transitions. Teams and live scores still use the show data.</p><div class="form-actions"><button id="pl-add" class="primary">Add current preview</button><button id="pl-in" ${!c?'disabled':''}>In</button><button id="pl-out">Out</button><button id="pl-next" ${!c?'disabled':''}>Next</button><button id="pl-play" ${!c?'disabled':''}>Play / Resume</button><button id="pl-pause">Pause</button><button id="pl-restart" ${!c?'disabled':''}>Select first</button></div><p id="playlist-status">${running?'Playing automatically':remaining?'Paused — graphic stays on air':'Manual playback'}</p><p class="help">Next takes the next item live. Play advances after each hold time and takes the last item out. Pause keeps the current graphic on air. Keep this control tab open for timed playback. Lineup items save the selected group and title/player phase; add each desired step in order.</p></section><section class="card"><h3>Running order · ${rows.length}/100</h3>${rows.length?rows.map((r,i)=>`<div data-pl-row="${esc(r.id)}" style="display:flex;gap:8px;flex-wrap:wrap;align-items:center;padding:12px 0;border-bottom:1px solid #344653"><button data-pl-select="${esc(r.id)}" class="${c?.id===r.id?'primary':''}">${i+1}. ${c?.id===r.id?'Selected':'Select'}</button><label>Name<input data-pl-name value="${esc(r.name)}" maxlength="100"></label><span>${esc(graphicNames[r.cue.type]||r.cue.type)} · ${esc(r.cue.team||'')}</span><label>Hold seconds<input data-pl-seconds type="number" min="1" max="300" value="${r.seconds}" style="width:90px"></label><button data-pl-move="-1" ${i===0?'disabled':''} aria-label="Move item ${i+1} up">↑</button><button data-pl-move="1" ${i===rows.length-1?'disabled':''} aria-label="Move item ${i+1} down">↓</button><button data-pl-load>Load to preview</button><button data-pl-replace>Replace with preview</button><button data-pl-delete>Remove</button></div>`).join(''):'<p>No items yet. Select and edit a graphic in the library, then use Add current preview.</p>'}</section>`;}
 function bind(root){const on=(id,fn)=>root.querySelector(id).onclick=async()=>{if(working)return;try{await fn();}catch(e){pause();toast(e.message,true);}};
  on('#pl-add',async()=>{const cue=structuredClone(getState().preview);if(cue.type==='none'){toast('Select a graphic in the library first.');return;}const row={id:crypto.randomUUID(),name:graphicNames[cue.type]||cue.type,seconds:cue.type==='transition'?Number(cue.transitionDuration)||3:8,cue};selected=row.id;await save([...items(),row]);});
  on('#pl-in',async()=>{pause();await take();});on('#pl-out',async()=>{pause();await out();render();});on('#pl-next',async()=>{pause();await advance();});root.querySelector('#pl-pause').onclick=pause;
  on('#pl-play',async()=>{if(running)return;stopLineup();if(remaining&&owned){running=true;schedule(remaining);}else await take(true);});
  on('#pl-restart',()=>{pause();remaining=0;selected=items()[0]?.id;render();});
  root.querySelectorAll('[data-pl-row]').forEach(el=>{const id=el.dataset.plRow;
   const run=fn=>async()=>{if(working)return;try{await fn();}catch(e){toast(e.message,true);}};
   el.querySelector('[data-pl-select]').onclick=()=>{pause();remaining=0;selected=id;render();};
   el.querySelector('[data-pl-name]').onchange=run(async()=>{await save(items().map(r=>r.id===id?{...r,name:el.querySelector('[data-pl-name]').value}:r));});
   el.querySelector('[data-pl-seconds]').onchange=run(async()=>{const seconds=Number(el.querySelector('[data-pl-seconds]').value);if(!Number.isFinite(seconds)||seconds<1||seconds>300)throw Error('Hold time must be 1–300 seconds.');await save(items().map(r=>r.id===id?{...r,seconds}:r));});
   el.querySelectorAll('[data-pl-move]').forEach(b=>b.onclick=run(async()=>{const rows=[...items()],i=rows.findIndex(r=>r.id===id),j=i+Number(b.dataset.plMove);if(j<0||j>=rows.length)return;[rows[i],rows[j]]=[rows[j],rows[i]];await save(rows);}));
   el.querySelector('[data-pl-load]').onclick=run(async()=>{pause();await act('preview',items().find(r=>r.id===id).cue);toast('Loaded into preview. Edit it in the graphics library.');});
   el.querySelector('[data-pl-replace]').onclick=run(()=>save(items().map(r=>r.id===id?{...r,cue:structuredClone(getState().preview)}:r)));
   el.querySelector('[data-pl-delete]').onclick=run(()=>save(items().filter(r=>r.id!==id)));
  });renderStatus();
 }
 return {view,bind,observe,pause};
}
