const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mark=t=>t.logo?`<img src="${esc(t.logo)}" alt="${esc(t.name)}">`:`<b>${esc(t.abbr)}</b>`;
const colors=t=>`--team:${esc(t.color||'#102b49')};--secondary:${esc(t.secondary||'#b5c6d3')}`;
export function kickoffText(start,now=Date.now()) {const target=Date.parse(start);if(!Number.isFinite(target))return '—:——:——';const sec=Math.max(0,Math.ceil((target-now)/1000));return `${Math.floor(sec/3600)}:${String(Math.floor(sec/60)%60).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}
export function countdownMarkup(s,c={}){return `<section class="kickoff-bug"><div class="kickoff-top"><b data-kickoff="${esc(s.branding.gameStart||'')}">—:——:——</b><span>${esc(c.countdownLabel||'TO KICKOFF')}</span></div><div class="kickoff-matchup">${esc(s.teams.away.shortName||s.teams.away.name)} AT ${esc(s.teams.home.shortName||s.teams.home.name)}</div></section>`;}
export function updateKickoff(root,now=Date.now()){for(const el of root.querySelectorAll('[data-kickoff]'))el.textContent=kickoffText(el.dataset.kickoff,now);}
export function newsGraphic(s,c){const t=s.teams[c.team||'away'],art=c.newsArt||'team',ids=[c.newsPlayerId,c.newsSecondPlayerId],people=ids.map(id=>t.roster.find(p=>p.id===id)).filter(Boolean),hasArtwork=art==='network'||(art!=='none'&&(c.newsShowLogo!==false||(['player','duo'].includes(art)&&people.slice(0,art==='duo'?2:1).some(p=>p.photo))));return `<section class="news-ribbon ${c.newsLabel===false?'no-label':''} news-art-${esc(art)} ${hasArtwork?'':'news-text-only'}" style="${c.newsTeamColor===false?'--team:#1a242b;--secondary:#afbfc6':colors(t)}"><div class="news-body"><div class="news-face"></div><div class="news-metal"></div><p>${esc(c.newsText||'')}</p></div>${c.newsLabel===false?'':`<div class="news-label">BREAKING NEWS</div>`}<div class="news-art">${art==='network'?(s.branding.networkLogo?`<img class="news-team-mark" src="${esc(s.branding.networkLogo)}" alt="Network">`:`<b>${esc(s.branding.network)}</b>`):art!=='none'?`${c.newsShowLogo===false?'':`<div class="news-team-mark">${mark(t)}</div>`}${['player','duo'].includes(art)?people.slice(0,art==='duo'?2:1).map(p=>p.photo?`<img class="news-person" src="${esc(p.photo)}" alt="${esc(p.name)}">`:'').join(''):''}`:''}</div></section>`;}
export function pregamePlayer(s,c){const t=s.teams[c.team||'away'],p=t.roster.find(p=>p.id===c.playerId)||t.roster[0]||{},words=String(p.name||'').split(' '),first=words.shift(),last=words.join(' ');return `<section class="pregame-player" style="${colors(t)}"><div class="pregame-player-face"></div><div class="pregame-player-logo">${mark(t)}</div><div class="pregame-player-photo">${p.photo?`<img src="${esc(p.photo)}" alt="${esc(p.name)}">`:`<b>${esc(p.number)}</b>`}</div><div class="pregame-player-rails"></div><div class="pregame-player-copy">${c.featureContext?`<small>${esc(c.featureContext)}</small>`:''}<h1><span>${esc(first)}</span>${esc(last||first)}</h1><p>${esc(c.featureText||'')}</p>${c.featureFooter?`<footer>${esc(c.featureFooter)}</footer>`:''}</div></section>`;}
export function studioTransition(s,c){if(c.transitionStyle==='pattern')return patternTransition(s,c);const team=c.transitionStyle==='teamwall',t=s.teams[c.team||'away'],image=team?t.logo:s.branding.secondaryLogo||s.branding.networkLogo;return `<section class="studio-transition ${team?'studio-team':'studio-network'}" style="${colors(t)}"><div class="studio-wall">${Array.from({length:7},(_,col)=>`<div class="studio-column" style="--column:${col}">${Array.from({length:10},()=>'<i></i>').join('')}</div>`).join('')}</div><div class="studio-color"><span>${esc(team?t.abbr:s.branding.network)}</span></div><div class="studio-emblem">${image?`<img src="${esc(image)}" alt="${esc(team?t.name:s.branding.network)}">`:`<strong>${esc(s.branding.network)}<b>${esc(s.branding.competition)}</b></strong>`}</div></section>`;}

function patternTransition(s,c){const t=s.teams[c.team||'away'];return `<section class="pattern-transition" style="${colors(t)}"><svg width="0" height="0" aria-hidden="true" style="position:absolute"><defs><filter id="team-tunnel-outline" x="-10%" y="-10%" width="120%" height="120%"><feMorphology in="SourceAlpha" operator="dilate" radius="2" result="outer"/><feMorphology in="SourceAlpha" operator="erode" radius="1" result="inner"/><feComposite in="outer" in2="inner" operator="out" result="edge"/><feFlood flood-color="white"/><feComposite in2="edge" operator="in"/></filter></defs></svg><div class="pattern-field">${Array.from({length:48},(_,i)=>`<i style="--tile:${i%8};--row:${Math.floor(i/8)}">${t.logo?`<img src="${esc(t.logo)}" alt="">`:''}</i>`).join('')}</div><div class="pattern-logo"><div class="pattern-solid">${mark(t)}</div><div class="pattern-outline">${mark(t)}</div></div><div class="pattern-title"><span></span><b>${esc(t.shortName||t.name)}</b><span></span></div></section>`;}
