export const leagues=['NFL','MLB','NBA','MLS'];
const paths={NFL:'football/nfl',NBA:'basketball/nba',MLS:'soccer/usa.1',MLB:'baseball/mlb'};
const text=v=>String(v??'');
function extraData(c,league,live,sit){
 const lines=[];
 if(live&&league==='MLB'&&sit.outs!==undefined)lines.push(`${sit.balls??0} B · ${sit.strikes??0} S · ${sit.outs} OUT`);
 const tv=c.broadcasts?.flatMap(b=>b.names||[]).join(' / ');if(tv)lines.push(tv);
 for(const group of c.leaders||[])for(const lead of (group.leaders||[]).slice(0,1))if(lead.athlete?.shortName&&lead.displayValue)lines.push(`${lead.athlete.shortName} · ${lead.displayValue}`);
 return lines.slice(0,4).join('\n');
}

export function espnGames(data,league){return (data.events||[]).flatMap(e=>{const c=e.competitions?.[0],status=c?.status||e.status;if(!c||!status)return [];const team=side=>{const t=c.competitors.find(x=>x.homeAway===side);if(!t)return null;return{id:text(t.id),name:t.team?.shortDisplayName||t.team?.name||t.team?.abbreviation,abbr:t.team?.abbreviation,logo:t.team?.logo||'',score:status.type?.state==='pre'?'':text(t.score),record:t.records?.find(r=>r.type==='total')?.summary||''};};const away=team('away'),home=team('home');if(!away||!home)return [];const live=status.type?.state==='in',sit=c.situation||{},poss=text(sit.possession);return [{id:league+':'+e.id,league,away,home,start:e.date,status:status.type?.shortDetail||status.type?.description||'',state:status.type?.state||'pre',possession:live?poss:'',ball:live?text(sit.possessionText):'',down:live?text(sit.downDistanceText):'',detail:extraData(c,league,live,sit)}];});}
export function mlbGames(data){return (data.dates||[]).flatMap(d=>d.games||[]).map(g=>{const live=g.status.abstractGameState==='Live',pre=g.status.abstractGameState==='Preview',l=g.linescore||{};const team=side=>{const t=g.teams[side];return{id:text(t.team.id),name:t.team.teamName||t.team.name,abbr:t.team.abbreviation||t.team.name,logo:`https://www.mlbstatic.com/team-logos/${t.team.id}.svg`,score:pre?'':text(t.score),record:t.leagueRecord?`${t.leagueRecord.wins}-${t.leagueRecord.losses}`:''};};return {id:'MLB:'+g.gamePk,league:'MLB',away:team('away'),home:team('home'),start:g.gameDate,state:pre?'pre':live?'in':'post',status:live&&l.currentInning?`${l.inningHalf||''} ${l.currentInningOrdinal||l.currentInning}`:g.status.detailedState,possession:live?text(l.offense?.team?.id):'',ball:'',down:'',detail:live&&l.outs!==undefined?`${l.balls??0} B · ${l.strikes??0} S · ${l.outs??0} OUT${l.offense?.first?' · 1B':''}${l.offense?.second?' · 2B':''}${l.offense?.third?' · 3B':''}`:[g.teams.away.probablePitcher?.fullName,g.teams.home.probablePitcher?.fullName].filter(Boolean).join(' vs ')};});}
export function nbaGames(data){return (data.scoreboard?.games||[]).map(g=>{const team=t=>({id:text(t.teamId),name:t.teamName,abbr:t.teamTricode,logo:'',score:g.gameStatus===1?'':text(t.score),record:t.wins!==undefined?`${t.wins}-${t.losses}`:''});return{id:'NBA:'+g.gameId,league:'NBA',away:team(g.awayTeam),home:team(g.homeTeam),start:g.gameTimeUTC,status:g.gameStatus===2?`Q${g.period}  |  ${text(g.gameClock).replace(/^PT(\d+)M([\d.]+)S$/,(_,m,sec)=>m+':'+String(Math.floor(Number(sec))).padStart(2,'0'))}`:g.gameStatusText,state:g.gameStatus===1?'pre':g.gameStatus===2?'in':'post',possession:'',ball:'',down:'',detail:''};});}
async function json(url){const r=await fetch(url,{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error(`Feed HTTP ${r.status}`);return r.json();}
export async function fetchLeague(league,date=''){
 if(league==='MLB'){try{return{games:mlbGames(await json('https://statsapi.mlb.com/api/v1/schedule?sportId=1&hydrate=team,linescore,probablePitcher,broadcasts'+(date?'&date='+date:''))),source:'MLB Stats API'};}catch{}}
 if(league==='NBA'&&!date){try{return{games:nbaGames(await json('https://cdn.nba.com/static/json/liveData/scoreboard/todaysScoreboard_00.json')),source:'NBA live data'};}catch{}}
 return{games:espnGames(await json('https://site.api.espn.com/apis/site/v2/sports/'+paths[league]+'/scoreboard?limit=100'+(date?'&dates='+date.replaceAll('-',''):'')),league),source:'ESPN'};
}
