import {esc} from './graphics.js?v=logos125';
let selected='',generation=0;
export function libraryView(){return `<div class="section-heading"><div><h2>Team library</h2><p>Save teams once. Choose a home and away team for each broadcast.</p></div></div><div id="team-library-content" aria-live="polite">Loading saved teams…</div>`;}
export async function bindLibrary({act,state,open,toast,imageFile}){
 const token=++generation,root=document.querySelector('#team-library-content');
 const request=async path=>{const r=await fetch(path);if(!r.ok)throw Error('Unable to load saved teams.');return r.json();};
 try{
  const data=await request('/api/teams');if(!root.isConnected||token!==generation)return;
  if(!data.teams.some(t=>t.id===selected))selected=data.teams[0]?.id||'';
  const opts=data.teams.map(t=>`<option value="${esc(t.id)}" ${t.id===selected?'selected':''}>${esc(t.name)} · ${t.players} players</option>`).join('');
  root.innerHTML=`<div class="card"><h3>Broadcast matchup</h3><div class="form-grid">${['away','home'].map(side=>`<div><strong>${side.toUpperCase()}: ${esc(state.teams[side].name)}</strong><p>${data.selected[side]?'Linked to saved team. Edits to players, coaches, logos and colors save back to its library entry.':'Custom show team — save a copy to keep it in the library.'}</p><button data-capture="${side}">Save ${side} as a new library team</button></div>`).join('')}</div></div><div class="card" style="margin-top:16px"><label>Saved team<select id="library-selection">${opts}</select></label><div id="library-detail"></div></div><form id="library-create" class="card" style="margin-top:16px"><h3>Add your own team</h3><div class="form-grid"><label>Team name<input name="name" required maxlength="50"></label><label>Abbreviation<input name="abbr" required maxlength="5"></label><label>Primary color<input name="color" type="color" value="#163d68"></label><label>Secondary color<input name="secondary" type="color" value="#ffffff"></label></div><button class="primary">Create team</button></form>`;
  async function detail(){
   root.querySelector('#library-detail').textContent='Loading team…';
   const id=selected,t=await request('/api/teams?id='+encodeURIComponent(id));if(!root.isConnected||selected!==id)return;
   const assigned=['away','home'].find(side=>data.selected[side]===id),src=t.source;
   root.querySelector('#library-detail').innerHTML=`<div class="library-team-heading"><span style="background:${esc(t.color)};border-color:${esc(t.secondary)}">${esc(t.abbr)}</span><div><h3>${esc(t.name)}</h3><p>${t.roster.length} players · ${t.staff.length} coaches · ${esc(t.record||'')}</p></div></div><details><summary>Edit team name, colors & upload logos</summary><form id="library-branding"><div class="form-grid">${[['name','Team name'],['shortName','Banner name'],['abbr','Abbreviation'],['record','Record']].map(([k,label])=>`<label>${label}<input name="${k}" value="${esc(t[k])}" maxlength="${k==='abbr'?5:50}"></label>`).join('')}<label>Primary color<input type="color" name="color" value="${esc(t.color)}"></label><label>Secondary color<input type="color" name="secondary" value="${esc(t.secondary)}"></label><label>Team logo<input name="logo" type="file" accept="image/png,image/jpeg,image/webp"></label><label>Banner logo / helmet<input name="heroLogo" type="file" accept="image/png,image/jpeg,image/webp"></label></div>${t.logo?`<img class="preview-photo" src="${esc(t.logo)}" alt="Saved team logo">`:''}<button class="primary">Save team identity</button></form></details>${src?`<p class="help">${src.season} ${esc(src.seasonType)} · Retrieved ${esc(src.fetchedAt.slice(0,10))}. ${esc(src.coachCoverage)}. Stats are a dated snapshot; unavailable values are not treated as zero.</p><p><a href="${esc(src.colors)}" target="_blank" rel="noopener">Team/roster source</a> · <a href="${esc(src.coaches)}" target="_blank" rel="noopener">Official coaching staff</a></p>`:''}<div class="form-actions">${['away','home'].map(side=>`<button data-assign="${side}" ${data.selected[side]===id?'disabled':''}>${data.selected[side]===id?'Assigned as':'Use as'} ${side}</button>`).join('')}</div>${assigned?`<div class="form-actions"><button data-edit="rosters">Edit players & stats</button><button data-edit="staff">Edit coaches</button><button data-edit="lineups">Assign lineup & special teams</button><button data-edit="branding">Upload logos & edit colors</button></div>`:'<p class="help">Assign to home or away to add/edit players and coaches. Logos and colors can be edited above at any time.</p>'}<details><summary>Players (${t.roster.length})</summary><div class="library-scroll"><table class="library-table"><thead><tr><th>#</th><th>Player</th><th>Position</th><th>Status</th><th>2026 stats</th></tr></thead><tbody>${t.roster.map(p=>`<tr><td>${esc(p.number)}</td><td>${esc(p.name)}</td><td>${esc(p.position)}</td><td>${esc(p.status||'—')}</td><td>${Object.entries(p.stats).map(([k,v])=>`${esc(k)} ${esc(v)}`).join(' · ')||esc(p.statsStatus||'Not entered')}</td></tr>`).join('')}</tbody></table></div></details><details><summary>Coaches (${t.staff.length})</summary><div class="library-scroll">${t.staff.map(c=>`<p><b>${esc(c.name)}</b> — ${esc(c.role)}</p>`).join('')}</div></details>`;
   root.querySelector('#library-branding').onsubmit=async e=>{e.preventDefault();try{const fd=new FormData(e.target),payload={id,...Object.fromEntries([...fd].filter(([k])=>!['logo','heroLogo'].includes(k)))};for(const k of ['logo','heroLogo']){const image=await imageFile(fd.get(k));if(image)payload[k]=image;}await act('library_branding',payload);toast('Team identity saved.');open('teams');}catch(e){toast(e.message,true);}};
   root.querySelectorAll('[data-assign]').forEach(b=>b.onclick=async()=>{try{b.disabled=true;await act('library_assign',{id,team:b.dataset.assign});toast('Team assigned. Scores and clocks retained.');open('teams');}catch{b.disabled=false;}});
   root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>open(b.dataset.edit,assigned));
  }
  root.querySelector('#library-selection').onchange=e=>{selected=e.target.value;detail().catch(e=>toast(e.message,true));};
  root.querySelectorAll('[data-capture]').forEach(b=>b.onclick=async()=>{try{const result=await act('library_capture',{team:b.dataset.capture});selected=result.lastLibraryTeam;open('teams');toast('Saved a reusable copy.');}catch{}});
  root.querySelector('#library-create').onsubmit=async e=>{e.preventDefault();try{const result=await act('library_create',Object.fromEntries(new FormData(e.target)));selected=result.lastLibraryTeam;open('teams');toast('Team created. Assign it to home or away to add personnel.');}catch{}};
  await detail();
 }catch(e){if(root.isConnected)root.textContent=e.message;}
}
